### ISSUE TITLE
Fix changes pending WG validation

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#103]
The published version of Vaccination has changes that seem unrequested, notably some examples that are not aligned with the Vaccination discussions. The official publication should not contain such changes
Tracing this, it seems that a cleanup was done that introduced meaningful changes. 
This issue is to revert those changes so that the changes applied to the main branch always reflect the approved changes (and of course some technical cleanup that is not functional).

**Comment by bdc-ehealth** [comment]
See Validation WG meeting minutes: https://wiki.hl7belgium.org/index.php?title=Minutes_-_FHIR_Validation_Group_2023-05-25#:~:text=Jose%20notes%20that%20his%20own%20examples%20are%20now%20not%20inline%20with%20the%20current%20community%20recommendations%2C%20and%20this%20caused%20his%20confusion.%20Jose%20retracts%20the%20need%20to%20republish%20and%20we%20will%20follow%20the%20process%20to%20change%20the%20examples%20too.

Also closing related superfluous PR.
