### ISSUE TITLE
TargetDisease

### ISSUE THREAD

**Issue by HanneVuegen** [hl7-be/vaccination#121]
For patient purposes it would be useful to mention the target disease of the vaccination. In Immunization R4, R5 and R6 the TargetDisease is mentionned in the 'ProtocolApplied' but for some reason this is barred in BeVaccination. Can an explanation for this be given?

**Comment by bdc-ehealth** [comment]
everything in protocolApplied, and thus also TargetDisease,  was removed in April '22  after a meeting with Anne Nerenhausen and J.C.Teixeira apparently: https://github.com/hl7-be/vaccination/pull/55

**Comment by HanneVuegen** [comment]
I understand that it is not the intention to register the vaccination program, but the Targetdisease is important information of the vaccination anyways. Maybe there are other options then the ProtocolApplied..?

**Comment by costateixeira** [comment]
If the Target disease can be for example "we want to vaccinate the patient against Gonorrhea by giving them the Meningococcal vaccine", then we should indeed consider restoring the protocolApplied. A change request will be done to FHIR core to adapt the language.

**Comment by m-shoop** [comment]
Similar to issue 116 - lowering the maximum cardinality of an element from the base spec reduces the possibility of re-use of software and of interoperability generally. 

Unless there is specific reason to exclude the protocolApplied element, for this reason it would be beneficial to keep it within the Belgium Vaccination resource.

**Comment by HanneVuegen** [comment]
@m-shoop some workgroups were planned to discuss issues regarding allergyintolerance and vaccination. I don't know if you're invited? If not I can ask to add you to the meeting requests? @costateixeira @bdc-ehealth

**Comment by m-shoop** [comment]
Thank you, Hanne. I don't currently see those workgroup invitations in my inbox - feel free to add me (mshoop@epic.com), though!

**Comment by KarlienHL7Belgium** [comment]
We should indeed consider restoring the protocolApplied. We need to agree on when we want to consider this change...
There seems to be a need for a mapping between pathologies and vaccination indications... to be further discussed

**Comment by KarlienHL7Belgium** [comment]
This should be part of the business decisions and rules. To be checked by RIZIV and @anne nerenhausen

**Comment by vmichie** [comment]
@KarlienHL7Belgium: For Vitalink, this issue has priority #3

**Comment by bdc-ehealth** [comment]
WG: we will handle this next time...

**Comment by bdc-ehealth** [comment]
@annenerenhausen provided this valueset. The current valueset was modified to include these "designations" and codes.
[Value Set Vaccination V1.0.xlsx](https://github.com/user-attachments/files/16111571/Value.Set.Vaccination.V1.0.xlsx)

**Comment by bdc-ehealth** [comment]
@ipollet
