### ISSUE TITLE
Feedback provided to HL7 International about Immunization.reportOrigin?

### ISSUE THREAD

**Issue by m-shoop** [hl7-be/vaccination#125]
In this profile we have introduced the element Immunization.extension.recorder which can be seen as a improved upon version of the element Immunization.reportOrigin in the base FHIR spec. Has HL7 Belgium given feedback to HL7 International that the base spec's support doesn't suit the needs of Belgium? It is probable that other locales share the same considerations, and that HL7 international should improve the base spec.

**Comment by KarlienHL7Belgium** [comment]
@costateixeira : can you please bring this to HL7 international

**Comment by costateixeira** [comment]
Hello

Is this about a recorder which may not be the performer? This could be done
with the performer data element.
I will ask in the appropriate group and get back to you.
Thanks

José
Kind regards

José

**Comment by KarlienHL7Belgium** [comment]
@m-shoop : can you please clarify José's question ?

**Comment by m-shoop** [comment]
Thanks José! To clarify, this is specific to the recorder element. 

The base spec does not reference a recorder (reportOrigin comes closes though, which is currently a set of four values: provider, record, recall, school). Our Belgian profile uses an extension for recorder - this seems like a useful addition beyond just the Belgian locale.
