### ISSUE TITLE
Add RelatedPerson as a valid reference for Immunization.extension.recorder

### ISSUE THREAD

**Issue by m-shoop** [hl7-be/vaccination#126]
In addition to the three existing Reference values ([Reference](http://hl7.org/fhir/R4/references.html#Reference)([BePatient](https://www.ehealth.fgov.be/standards/fhir/core/2.0.0/StructureDefinition-be-patient.html) | [BePractitioner](https://www.ehealth.fgov.be/standards/fhir/core/2.0.0/StructureDefinition-be-practitioner.html) | [BeOrganization](https://www.ehealth.fgov.be/standards/fhir/core/2.0.0/StructureDefinition-be-organization.html)), it seems valid to also allow RelatedPerson in this extension.

**Comment by KarlienHL7Belgium** [comment]
The WG considers that this does not need to be added.
Additionnally the BeRelatedPerson profile will have to be created first, this will be done in the WG core profile but will take up some discussion
