### ISSUE TITLE
Which is authoritative: logical models or profiles?

### ISSUE THREAD

**Issue by m-shoop** [hl7-be/vaccination#127]
There are two potentially contradicting set of resources in Belgium HL7's IG for developers to understand the Belgian Vaccination FHIR resource: the logical model FHIR representation (https://www.ehealth.fgov.be/standards/fhir/vaccination/StructureDefinition-be-model-vaccination.html) and the FHIR profile (https://www.ehealth.fgov.be/standards/fhir/vaccination/StructureDefinition-be-vaccination.html). 

Does a developer need to consult both? If so, what is each meant to convey for a developer's ability to implement the resource? And if there does arise a contradiction between the two, which is authoritative over the other?

If one is sufficient and authoritative, it may make sense to remove the other from the IG to simplify documentation.

**Comment by KarlienHL7Belgium** [comment]
The FHIR profile is authorative. The logical model should be aligned with the FHIR profile though.

What are the potentially contradicting set of resources @m-shoop ?

**Comment by costateixeira** [comment]
@m-shoop is this still an issue?
The documentation includes  the functional view of the data needs (logical model) and the actual implementable profile. We cannot remove the profile and I don't think we'd consider removing the functional model as simplifying documentation.

**Comment by bdc-ehealth** [comment]
@m-shoop We will close this one for now, please feel free to reopen it if needed.
