### ISSUE TITLE
lotNumber and expirationDate max cardinality and feedback to HL7 International

### ISSUE THREAD

**Issue by m-shoop** [hl7-be/vaccination#128]
The administeredProduct extension (BeAdministeredProduct ) per issues 49 and 66 appears to have been created to represent the vaccine as a Medication reference which the base spec does not support. This reduces interoperability since elements that have a max cardinality of greater than 0 in the base spec now have a max cardinality of 0 in the Belgian profile. 

Has Belgium HL7 submitted feedback to HL7 International about representing the vaccine as a Medication reference? It's likely that Belgium's considerations apply to other locales, as well, and that the base resource should be expanded to support the Medication reference.

**Comment by KarlienHL7Belgium** [comment]
We are working with R4 in Belgium. We do understand that this might cause interoperability issues cross-border.
About the cardinality: it was put to 0 as it is part of the administered product. @costateixeira : is this correct ?

HL7 Belgium brought it to HL7 int'l, and as such it was considered in R5

**Comment by costateixeira** [comment]
Yes, we have submitted feedback to HL7 international and the feedback was indeed accepted and the resource expanded: the extensions we need in Belgium have been moved to the core resource in R5.
https://hl7.org/fhir/R5/immunization-definitions.html#Immunization.administeredProduct
Can this issue be closed? or is there any other activity or clarification required?

**Comment by bdc-ehealth** [comment]
@m-shoop We will close the issue for now, feel free to reopen it if needed.

**Comment by m-shoop** [comment]
This is excellent news! 

Yes I agree this can be closed.
