### ISSUE TITLE
Remove ambiguity in Must Support definition for data prodcuers

### ISSUE THREAD

**Issue by m-shoop** [hl7-be/vaccination#129]
_Adding this feedback here because I noticed it while reviewing the BeVaccination resource but let me know if this should be moved to a different GitHub since the feedback pertains to the core guidance rather than just the Belgium Vaccination resource._
For data producers, rather than the ambiguously stated 'SHOULD populate the element when the information is available' it is clearer to say 'SHALL include this element if a value is known and allowed to be shared.' This will remove an ambiguity for implementers on what is expected.

Direct link: https://www.ehealth.fgov.be/standards/fhir/core/2.0.0/conventions.html#must-support

**Comment by KarlienHL7Belgium** [comment]
WG does not agree on changing the wording as this changes the meaning of must-support
