### ISSUE TITLE
Authentification problem

### ISSUE THREAD

**Issue by ZorgiLoic** [hl7-be/vaccination#130]
Hi, 

We are trying to connect to the vaccination vault but we receive some errors :
**Request :** 
curl --location '
[http://153.89.154.106/rsw.vault.fhir/Patient/_search'](http://153.89.154.106/rsw.vault.fhir/Patient/_search%27)
\
--header 'client_niss: 80052732397' \
--header 'application_identifier: XCare' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'patient.identifier=
[https://www.ehealth.fgov.be/standards/fhir/NamingSystem/ssin|80052732397'](https://www.ehealth.fgov.be/standards/fhir/NamingSystem/ssin%7C80052732397%27)
**Response :**
{
    "resourceType": "OperationOutcome",
    "id": "Unauthorized",
    "issue": [
        {
            "severity": "fatal",
            "code": "processing",
            "details": {
                "coding": [
                    {
                        "system": "vault.error.codes",
                        "code": "",
                        "display": "Access token requisition failed"
                    }
                ]
            }
        }
    ]
}
Can you show me where's the problem ?
With my user I can access to Vaccination on RSW acceptance.
Kind regards,

**Comment by bdc-ehealth** [comment]
@ZorgiLoic ,

Hello Loic, I think you will have to take that up with support@rsw.be and support@ehealth.fgov.be

**Comment by ZorgiLoic** [comment]
Ok thanks.
