### ISSUE TITLE
Constraint be-rule-vaccination-1 validates too much

### ISSUE THREAD

**Issue by smals-bvv** [hl7-be/vaccination#148]
https://github.com/hl7-be/vaccination/blob/74be26076cd447fe05722e8868fbdbe1ea1644be/input/fsh/profiles/BeVaccination.fsh#L88

Here the constraint is checking if vaccineCode.coding.code equals 'other' while technically it's not possible to have other as there is a required terminology binding with ValueSet BeVSVaccineCode. The second part of the constraint is correct.

It's not that the first part of the constraint is wrong but it should never be possible according to the strict binding to have the code "other". To avoid confusion, I suggest this constraint is changed to the following:
`vaccineCode.coding.where(code = '787859002' and system = 'http://snomed.info/sct').exists() implies vaccineCode.text.exists()`

**Comment by jmp-ehealth** [comment]
@smals-bvv 
Thanks for your feedback
We will check this issue on Mon 22/7
Regards
JM

**Comment by bdc-ehealth** [comment]
@smals-bvv ,

I agree this is a possible source of confusion, but there still exists a value #other in the valueset (which is a combination of SNOMED CT codes and a code from BeCSVaccinationCode . This code has been added some time ago, and was never officially withdrawn by the HL7 Workgroup. I would like to have the confirmation of the HL7 Workgroup to remove this value.

**Comment by smals-bvv** [comment]
@bdc-ehealth ,
Thanks for taking my feedback. I missed the fact that the ValueSet also includes that code from BeCSVaccinationCode (https://build.fhir.org/ig/hl7-be/vaccination/branches/releasecandidate/CodeSystem-be-cs-vaccine-code.html).
When I was testing the constraint I forgot to add the system in the coding for other.
When doing so, it works as expected.
![image](https://github.com/user-attachments/assets/0fef7a94-aa82-4c75-a8a9-59abe8eb5a99)

For me this was only a technical remark, not a functional. If the business wanted to have both the "other" code and the snomed one that represents "unspecified vaccine", for me it's ok to keep it.

**Comment by bdc-ehealth** [comment]
Both values will stay in. Approved by validation team on 29/08/2024
