### ISSUE TITLE
Verify constraints - especially those that are "error"

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#164]
The constraint be-rule-vaccination-4 seems too strict - has it been checked with a working and a failing example? 
I haven't checked further nor i find it easy to debug anyway, but what concerns me is the expression that has severity "error": encounter.empty() or encounter.resolve().location.location.resolve().type.coding.memberOf('https://www.ehealth.fgov.be/standards/fhir/vaccination/ValueSet/be-vs-care-location').anyTrue() , does the anyTrue refer to the several locations? or the several type.coding? Also, the location valueset - is it ok? The core spec binding is extensible. And how would this work with logical references?

With this, I am not so sure the constraint should exist or be "error", because it means that if we have an error in the expression, any resource with an encounter would fail.
Suggest lowering the severity or removing the constraint altogether - also for be-rule-vaccination-3

**Comment by HanneVuegen** [comment]
We did some extra testing based on the current vaccinnet data. Encounter.location is especially important to add information about the country of vaccination (pandemic experience and WHO expectations).  This constraint makes it impossible to simply add the most important information. I follow you José, so I suggest a technical fix:
-  remove the constraint 4, and add expected behaviour and valueset in the guidance 
- or change the constraint to be less strict

@bdc-ehealth @costateixeira

**Comment by katrijnbaetens** [comment]
line 92 of the example: you need to add this type block to get trough the validator, however, I don't have this info available, nor do I need it
`"type": [
        {
          "coding": [
            {
              "code": "abroad",
              "system": "https://www.ehealth.fgov.be/standards/fhir/vaccination/CodeSystem/be-cs-care-location"
            }
          ]
        }
      ]`
[EncounterExample_basedOnRecordVaccinnet1.json](https://github.com/user-attachments/files/16815078/EncounterExample_basedOnRecordVaccinnet1.json)

**Comment by bdc-ehealth** [comment]
@katrijnbaetens , thank you for the clear example. According to #92 (beware: version 1.3 in Dutch is mixed up here #151 ), if there is a location, at least one should have the values from the specified valueset. So I could not completely remove the invariant, but I relaxed it.
This is the validation output after relaxing the rule:
```
FHIR Validation tool Version 6.3.23 (Git# 2721ebb8c60b). Built 2024-08-28T18:46:12.471Z (43 hours old)
  Java:   18 from C:\openjdk-18\jdk-18 on amd64 (64bit). 8148MB available
  Paths:  Current = C:\Temp\empty\vaccination, Package Cache = C:\Users\eh089\.fhir\packages
  Params: c:\Temp\empty\vaccination\test\vaccinnet.json -version 4.0.1 -ig hl7.fhir.be.vaccination#dev
  Locale: United States/US
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4576 resources (01:07.738)
  Load hl7.fhir.uv.extensions.r5#5.1.0 - 1396 resources (00:36.211)
  Load hl7.terminology#6.0.2 - 4243 resources (00:18.355)
  Load hl7.terminology.r5#6.0.2 - 4243 resources (00:18.371)
  Load hl7.fhir.uv.extensions#5.2.0-ballot - 702 resources (00:15.319)
  Terminology server http://tx.fhir.org - Version Connected to Terminology Server at http://tx.fhir.org (00:02.998)
  Load hl7.terminology.r4#6.0.2 - 4243 resources (00:18.649)
  Load hl7.fhir.uv.extensions.r4#5.1.0 - 1396 resources (00:04.332)
  Load hl7.fhir.be.core#current$releasecandidate+  .. load IG from hl7.terminology.r4#5.5.0
 - 3633 resources (00:52.339)
  Load hl7.fhir.be.core#2.0.0 - 23 resources (00:02.213)
  Load hl7.terminology#3.1.0 - 4117 resources (00:29.514)
  Load hl7.fhir.be.medication#1.0.0 - 7 resources (00:00.292)
  Load hl7.terminology.r4#3.1.0 - 4117 resources (00:10.019)
  Load hl7.fhir.be.core-clinical#1.0.0 - 19 resources (00:00.024)
  Load hl7.fhir.be.vaccination#dev - 27 resources (00:00.039)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.1.0, hl7.fhir.uv.extensions.r5#5.1.0, hl7.terminology#6.0.2, hl7.terminology.r5#6.0.2, hl7.fhir.uv.extensions#5.2.0-ballot, hl7.terminology.r4#6.0.2, hl7.fhir.uv.extensions.r4#5.1.0, 
hl7.fhir.be.core#2.0.0, hl7.terminology#3.1.0, hl7.fhir.be.medication#1.0.0, hl7.terminology.r4#3.1.0, hl7.fhir.be.core-clinical#1.0.0, hl7.fhir.be.vaccination#dev]
  Terminology Cache at c:\temp\default-tx-cache
  Get set...  go (00:00.248)
Cached new session. Cache size = 1
Validating
  Validate c:\Temp\empty\vaccination\test\vaccinnet.json
Validate Immunization against http://hl7.org/fhir/StructureDefinition/Immunization|4.0.1..........20..........40....  Load hl7.fhir.be.medication#1.0.0 - 0 resources (00:04.888)
......60..........80.........|
Validate Immunization against https://www.ehealth.fgov.be/standards/fhir/vaccination/StructureDefinition/be-vaccination..........20..........40..........60.......|
 00:00.576
Done. Times: Loading: 04:37.759, validation: 00:05.465. Memory = 771Mb

Success: 0 errors, 3 warnings, 2 notes
  Information @ Immunization.route (line 80, col6): Reference to draft CodeSystem https://www.ehealth.fgov.be/standards/fhir/vaccination/CodeSystem/be-cs-vaccination-administration-route|1.0.4
  Information @ Immunization.extension[1].extension[0].value.ofType(CodeableConcept).coding[0].system (line 26, col18): Het CodeSystem https://www.ehealth.fgov.be/standards/fhir/medication/NamingSystem/be-ns-cnk-codes is onbekend
  Warning @ Immunization.contained[1]/*Encounter/demo-encounter*/.class (line 100, col8): A code with no system has no defined 
meaning, and it cannot be validated. A system should be provided
  Warning @ Immunization.extension[1].extension[0].value.ofType(CodeableConcept).coding[0].system (line 29, col123): URL value 
'https://www.ehealth.fgov.be/standards/fhir/medication/NamingSystem/be-ns-cnk-codes' does not resolve
  Warning @ Immunization (line 1, col2): Constraint failed: dom-6: 'A resource should have narrative for robust management' (defined in http://hl7.org/fhir/StructureDefinition/DomainResource) (Best Practice Recommendation)
Done. Times: Loading: 04:37.759, validation: 00:05.465. Max Memory = 7Gb
```

**Comment by costateixeira** [comment]
Disagree that one example is enough - and I think that example would not justify the changes to the expression that make it more robust (those changes are correct, by the way, just don't see if they are enough). But will open another issue to point at the gaps that may still exist in the expression.

**Comment by costateixeira** [comment]
Please see #168 for follow up on the invariants
