### ISSUE TITLE
Type (VaccineType is Primo Vaccin or Rappel) : must be series from ProtocolApplied in place of reason code?

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#19]
Type (the VaccineType is Primo Vaccin or Rappel) : must be series from ProtocolApplied in place of reason code ?

**Comment by costateixeira** [comment]
Should not be reasonCode. Should be protocolApplied

**Comment by bdc-ehealth** [comment]
duplicate of #12
