### ISSUE TITLE
Create a Belgian ValueSet for VaccineCode

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#3]

**Comment by costateixeira** [comment]
VaccineCode is not the code of the product, but the code for the vaccine.
**Change the field description to indicate "The code for the type of vaccine, typically identified by the disease(s) it covers. For example MMR, HPV, Tetanus, DTPa".**
**Add an initial draft ValueSet is sent by Anne.**
**+ Add the code for "Unspecified vaccine code" for Vaccinnet/eVax.**

**Comment by bdc-ehealth** [comment]
Needs to be completed by the NRC

**Comment by bdc-ehealth** [comment]
ValueSet exists, but not yet added to profile.
