### ISSUE TITLE
Proposal to limit this package to vaccination and rename it to vaccination

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/vaccination#33]
Only resources related to vaccination will remain here, we will make a new package for allergyIntolerance:

vaccination
BeVaccination
BeExtVaccinationOriginalOrder
BeExtAdministeredProduct
BeExtVaccinationLocation
BeExtVaccinationConfirmationStatus
BeVSVaccinationConfirmationStatus
BeCSVaccinationConfirmationStatus
BeVSVaccinationStatusReason
BeCSStatusReason
BeVSVaccineAdministrationRoute
BeCSVaccineAdministrationRoute

**Comment by bdc-ehealth** [comment]
@costateixeira This is a preparation for the new structure...

**Comment by costateixeira** [comment]
This has no objections for the technical part, but the communication should be clear that this is still part of the same careset "Patient Dossier", part of the project Patient Health Record.
