### ISSUE TITLE
Location might conflict with encounter field

### ISSUE THREAD

**Issue by stvb** [hl7-be/vaccination#44]
The be-ext-vaccination-location extension indicates where the vaccination took place. However, the "encounter" reference could already have information on the appointment location (and much more context information).  This could lead to conflicts or duplication of information. 

Wouldn't it be better to require an Encounter to be present to capture the context of the immunization ? 

Kind regards,
Steven

**Comment by costateixeira** [comment]
We agreed to remove the location extension, and instead use the .encounter.
The examples in the spec use contained resources, but we don't have any requirement on contained or external resources. We just use a Encounter resource.
Agreed on 5-5-2022

**Comment by HanneVuegen** [comment]
@stvb, can you have a look at my arguments: https://github.com/hl7-be/vaccination/issues/116
