### ISSUE TITLE
Create NamingSystems for the Belgian CodeSystems - CNK, VaccinnetCode, CTI (?) Extended

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#6]

**Comment by costateixeira** [comment]
https://ehealth.fgov.be/standards/fhir/NamingSystem-be-ns-cnk-codes.html
https://www.ehealth.fgov.be/standards/fhir/NamingSystem/be-ns-cti-extended-code
1. Missing VaccinnetCodes?
2. check consistency (www.)

**Comment by costateixeira** [comment]
Vaccinet code is CNK code plus package codes. 
Vaccinnet has also restricted codes (which do not correspond to SAMv2 codes) and are not to be used outside Vaccinnet - for example Sputnik Covid vaccine.

**Comment by costateixeira** [comment]
Vaccinnet NamingSystem to be created in this working group.
Proposal: 
**https://www.ehealth.fgov.be/standards/fhir/NamingSystem/be-ns-vaccinnet-product-code**

**Comment by bdc-ehealth** [comment]
cti extended and cnk-codes are now in https://build.fhir.org/ig/hl7-be/medication, after publication, they will be in https://www.ehealth.fgov.be/standards/fhir/medication. 

Adding dependency to the package
