### ISSUE TITLE
Add reaction CodeableConcept extension and a valueset

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#65]
The valueset can be the same as is for the AllergyIntolerance risk manifestation.
We could add a code for Clinical finding, but technically this is not needed - we can add simply use the CodeableConcept.text as normal in FHIR.

The Business Rule should be updated for alignment - we meet the same requirement without having a new SNOMED code.

**Comment by costateixeira** [comment]
Approved on 5-5-2022

**Comment by bdc-ehealth** [comment]
Reference is present in Invariant: be-rule-vaccination-3

The value set is in the core-clinical package because it is transversal.  Open issue there

**Comment by bdc-ehealth** [comment]
No changes needed in vaccination.
