### ISSUE TITLE
Add Backbone for Product and remove lot and expiration from top resource

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#66]
We have the (complex) extension administeredProduct which contains 
* reference (not commonly expected)
* code of the product)
* lot 
* expiry
In the normal case, the product will be identified by the code + lot + expiry, and not a reference.
With this, we'd have 2 places for lot and expiration, so to avoid that we remove the Immunization.lot and Immunization.expiryDate (i.e. we make them forbidden - 0..0 )
No change to the functional spec, this is just a technical implementation change.
Agreed on 5-5-22

**Comment by bdc-ehealth** [comment]
Duplicate from https://github.com/hl7-be/vaccination/issues/49 . No changes needed.
