### ISSUE TITLE
Addition of reasonCode as MS + valueset

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/vaccination#82]
see https://be-ehealth-standards.atlassian.net/jira/servicedesk/projects/ESI/queues/custom/19/ESI-103

**Comment by bdc-ehealth** [comment]
extract from the issue above containing all necessary info:
I have posted this question on FHIR chat today https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Vaccine.20given.20because.20exposure 
How and where in the immunization resource would you represent the information that the vaccine is given because the subject was exposed to a risk like exposure to monkeypox? Would you use Immunization.reasonCode element? And if so, would you populate it with SNOMED CT event concepts like 1290711000000105 |Exposure to monkeypox virus (event)| or would you use 409516001 |Post-exposure prophylaxis (procedure)| to convey the notion that the vaccine is given because of pre-exposition and use the Immunization.reasonReference element to further specify this? Now the second option brings me to ask if an exposure event concept can be used as a Problem in a problem resource. I'd say no when I look at the resource but an event can be the reason for admission and in the case of suspected exposure to a risk, you won't get any other diagnosis then that at the end of the consultation so how would you record this? How do you record and where a patient coming because he/she was exposed to a risk, that has currently no complaints or signs, and that gets a vaccine as prophylaxis against this risk transforming into a disease?
The interest of 409516001 |Post-exposure prophylaxis (procedure)| is that you also have 1137457009 |Pre-exposure prophylaxis (procedure)| which is applicable to all other vaccines given to prevent a risk one has never been exposed to. The exact nature of the risk prevented is actually known through the name of the vaccine concept itself and it might be redundant to try to precoordinate more the immunization reason, especially is one links a full report in Immunization.reasonReference.
I welcome your opinion on this as we are busy testing the BE immunization profile and the question was asked by users with a high degree of urgency.
I would welcome your opinion there and/or at our next SNOMED on FHIR meeting both in this and more generally on where in FHIR one is supposed to record an event that lead to a disorder, a symptom, or a risk, provoking a need for evaluation. We have been repeatedly asked by clinicians to add Event concepts to the list of the reasons for admission. And yes it fits real life needs when someone came because an event happened and you don't know yet what consequences this event had if any on the patient. But what does FHIR make of that, in which "box" do we put this info? Is it in http://www.hl7.org/fhir/eventdefinition.html or is that supposed to house only "medical events" (=procedures?)? If it's right to record a fall or an accident etc using EventDefinition, how do you hook this resource to the rest, to the disorder, the symptoms or indeed here the vaccination procedure?

**Comment by costateixeira** [comment]
Was there a WG meeting for this? I don't recall the issue, most likely it is something that we had already discussed. Since you usually take good notes of the meetings, I am looking where this was added
