### ISSUE TITLE
difference between the statusReason and the reasonCode. These 2 concepts can generate conflicts

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#9]
I don’t understand the difference between the “statusReason”(indicates the reason the immunization event was not performed) and the reasonCode (Why vaccination has occurred or not). These 2 concepts can generate conflicts and they are both

**Comment by bdc-ehealth** [comment]
@annenerenhausen Is this about the illness to prevent 
Reference(Condition | Observation | DiagnosticReport) ? Whereas the statusReason is the practical reason why the immunization did (not) happen?

**Comment by bdc-ehealth** [comment]
Indeed. #82 is now using this value.
